"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
const queryClient = new QueryClient();
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "sonner";

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryClientProvider client={queryClient}>
			<html lang="en">
				<body className={`${inter.className} antialiased bg-slate-300 `}>
					<main> {children}</main>
					<Toaster></Toaster>
				</body>
			</html>
		</QueryClientProvider>
	);
}
