import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProviderWrapper from "../providers/session-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Authentication page",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	session,
}: Readonly<{
	children: React.ReactNode;
	session: any;
}>) {
	return (
		<html lang="en">
			<SessionProviderWrapper session={session}>
				<body className={`${inter.className} antialiased bg-slate-300`}>
					{children}
				</body>
			</SessionProviderWrapper>
		</html>
	);
}
